Prise en main/createschema
signaux-faibles/documentation pull request #8
Opened 2020-04-23 10:44 UTC by chrnin

Une petite modification de la doc relative à l'intégration de la création du schéma postgres par le binaire datapi.

2020-04-23 11:41 UTC, adrienjoly requested changes

2020-04-23 11:41 UTC, adrienjoly commented on prise-en-main.md
> +Exécutez les commandes suivantes:
une des commandes fournies dessous repose encore sur `cat db-schema.sql` => il faut peut etre déplacer cette étape plus tard, si on veut retirer la recupération du fichier `db-schema.sql`

2020-04-29 11:25 UTC, chrnin commented on prise-en-main.md
> +Exécutez les commandes suivantes:
au temps pour moi, je viens de pousser la modif.

2020-04-29 11:33 UTC, adrienjoly approved these changes
Good job!

J'ai suggéré deux modifs optionnelles, à toi de voir si ça vaut le coup ou pas.

2020-04-29 11:33 UTC, adrienjoly commented on prise-en-main.md
> +$ ~/go/bin/datapi -createschema
[optionnel] Suggestion, dans le cas où GOPATH ne serait pas dans `~/go`:

```suggestion
$ $(go env GOPATH)/bin/datapi -createschema
```

2020-04-29 11:33 UTC, adrienjoly commented on prise-en-main.md
> +$ ~/go/bin/datapi -api
[optionnel] Suggestion, dans le cas où GOPATH ne serait pas dans `~/go`:

```suggestion
$ $(go env GOPATH)/bin/datapi -api
```

2020-04-29 11:47 UTC, chrnin commented
Ah bien vu, je me suis demandé si on pouvait pas utiliser $GOPATH et sur mon système elle n'est pas définie, du coup j'avais reculé, go env répond bien à la question :)

2020-04-29 11:48 UTC, merged

2020-04-29 11:51 UTC, adrienjoly commented
Pour info, $GOPATH n'était pas défini sur mon environnement non plus, c'est comme ça que j'ai découvert cette manière de faire. Content qu'elle te convienne ^^